- hosts: germany
  vars:
    nginx_port: 8080
    conf_dir: /etc/nginx
    html_dir: /usr/share/nginx/html
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update nginx conf
      ansible.builtin.template:
        src: ./files/nginx.conf
        dest: "{{conf_dir}}/nginx.conf"
      notify:
        - restart nginx
      become: yes

    - name: update nginx index.html
      ansible.builtin.template:
        src: ./files/index.html
        dest: "{{html_dir}}/index.html"
      notify:
        - restart nginx
      become: yes
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
