- hosts: germany
  vars:
    server_name: "this is server {{ ansible_nodename }}"
    deploy_time: "{{ ansible_date_time['date'] }}"
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: add template
      ansible.builtin.template:
        src: ./files/index.html
        dest: /usr/share/nginx/html/index.html
      become: yes
    - name: show server_name
      ansible.builtin.debug:
        msg: server_name={{ server_name }}

